# Generated by Django 3.2.12 on 2022-04-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HotelRestaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(null=True, upload_to='tour_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('duration_text', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('count', models.IntegerField(default=0)),
                ('short_description', models.TextField()),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='tour_video/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelRestaurant.city')),
                ('gallery', models.ManyToManyField(blank=True, null=True, related_name='gallery_tour', to='tour_pack.Gallery')),
                ('place', models.ManyToManyField(blank=True, null=True, related_name='place_tour', to='tour_pack.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('count', models.IntegerField(verbose_name='Количество людей')),
                ('confirm', models.BooleanField(default=True, verbose_name='Подтвержден')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_pack.tour', verbose_name='Название тура')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordera', to='tour_pack.tourorder')),
            ],
        ),
    ]
