# Generated by Django 3.2.12 on 2022-04-21 15:08

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(null=True, upload_to='tour_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(null=True, upload_to='tour_images/')),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('duration_text', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('count', models.IntegerField(default=0)),
                ('short_description', models.TextField()),
                ('description', django_quill.fields.QuillField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_pack.city')),
                ('gallery', models.ManyToManyField(related_name='gallery_tour', to='tour_pack.Gallery')),
                ('place', models.ManyToManyField(related_name='place_tour', to='tour_pack.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
