# Generated by Django 3.2.12 on 2022-03-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRestaurantNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=128)),
                ('avatarka', models.ImageField(upload_to='avatarka/restaurants/')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_pack.city')),
                ('stol_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_pack.hotelrestaurantnum')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=128)),
                ('avatarka', models.ImageField(upload_to='avatarka/hotels/')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_pack.city')),
                ('room_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_pack.hotelrestaurantnum')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=11)),
                ('booking_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('Not reserved', 'Not reserved'), ('Reserved', 'Reserved')], default=False, max_length=12)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_pack.hotels')),
                ('reserv_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_pack.hotelrestaurantnum')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour_pack.restaurants')),
            ],
            options={
                'unique_together': {('booking_date', 'reserv_num')},
            },
        ),
    ]
