# Generated by Django 3.2.12 on 2022-04-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='room_num',
        ),
    ]
