# Generated by Django 3.2.12 on 2022-04-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0002_auto_20220421_0043'),
        ('tour_pack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelRestaurant.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
