# Generated by Django 3.2.12 on 2022-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image3d',
            field=models.ImageField(null=True, upload_to='tour_images/'),
        ),
    ]
