# Generated by Django 3.2.12 on 2022-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pack', '0002_auto_20220421_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='gallery',
            field=models.ManyToManyField(related_name='gallery_tour', to='tour_pack.Gallery'),
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ManyToManyField(related_name='place_tour', to='tour_pack.Place'),
        ),
    ]
