# Generated by Django 3.2.12 on 2022-04-21 16:44

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pack', '0003_auto_20220421_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, related_name='gallery_tour', to='tour_pack.Gallery'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='place',
            field=models.ManyToManyField(blank=True, null=True, related_name='place_tour', to='tour_pack.Place'),
        ),
    ]
