# Generated by Django 3.2.12 on 2022-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pack', '0004_auto_20220421_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tour_video/'),
        ),
    ]
