# Generated by Django 3.2.12 on 2022-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pack', '0006_tourorder_usertour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourorder',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
