# Generated by Django 3.2.12 on 2022-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pack', '0007_alter_tourorder_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourorder',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourorder',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
