# Generated by Django 3.2.12 on 2022-04-20 18:43

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220419_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(),
        ),
    ]
