# Generated by Django 3.2.12 on 2022-04-20 19:35

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220421_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
    ]
