# Generated by Django 3.2.12 on 2022-04-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratehotels',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_hotel', to='HotelRestaurant.roomshotel'),
            preserve_default=False,
        ),
    ]
