# Generated by Django 3.2.12 on 2022-04-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0002_ratehotels_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratehotels',
            name='room',
        ),
    ]
