# Generated by Django 3.2.12 on 2022-05-02 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='date_from',
            field=models.DateField(default=datetime.date(2022, 5, 2)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='date_to',
            field=models.DateField(default=datetime.date(2022, 5, 3)),
        ),
    ]
