# Generated by Django 3.2.12 on 2022-04-21 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0002_auto_20220421_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='date_from',
            field=models.DateField(default=datetime.date(2022, 4, 22)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='date_to',
            field=models.DateField(default=datetime.date(2022, 4, 23)),
        ),
    ]
