# Generated by Django 3.2.12 on 2022-05-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0003_auto_20220502_1517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratehotels',
            unique_together=set(),
        ),
    ]
