# Generated by Django 3.2.12 on 2022-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0003_remove_hotelbooking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Записан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(null=True, upload_to='hotel_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='photo_hotel',
        ),
        migrations.RemoveField(
            model_name='roomshotel',
            name='photo_room',
        ),
        migrations.AddField(
            model_name='hotels',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, related_name='gallery_hotel', to='HotelRestaurant.Gallery'),
        ),
        migrations.AddField(
            model_name='roomshotel',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, related_name='gallery_room', to='HotelRestaurant.Gallery'),
        ),
    ]
