# Generated by Django 3.2.12 on 2022-04-24 18:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0004_auto_20220424_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='date_from',
            field=models.DateField(default=datetime.date(2022, 4, 25)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='date_to',
            field=models.DateField(default=datetime.date(2022, 4, 26)),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='HotelRestaurant.roomshotel'),
        ),
        migrations.AlterField(
            model_name='ratehotels',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reviewtotalhotel',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
