# Generated by Django 3.2.12 on 2022-05-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0004_alter_ratehotels_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rateroom',
            unique_together=set(),
        ),
    ]
