# Generated by Django 3.2.12 on 2022-04-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelRestaurant', '0004_auto_20220424_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='HotelRestaurant.roomshotel'),
        ),
    ]
